site_name: BoxLambda Documentation
site_url: !ENV READTHEDOCS_CANONICAL_URL

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: material
    logo: assets/boxlambda_logo_simple_white.png
    favicon: assets/boxlambda_logo_simple.png
    features:
      - navigation.tracking
      - navigation.instant
      - navigation.sections
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - navigation.top

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/@2Lysens
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/epsilon537.bsky.social
    - icon: fontawesome/brands/github
      link: https://github.com/epsilon537/boxlambda
    - icon: fontawesome/solid/paper-plane
      link: mailto:ruben.lysens2@gmail.com

repo_url: https://github.com/epsilon537/boxlambda

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4

nav:
    - About:
        - About: index.md
        - The Requirements: requirements.md
    - Terms and Abbreviations: terms-and-abbreviations.md
    - Installation:
        - Prerequisites: prerequisites.md
        - Peripherals (PMODs): pmods.md
        - Installation: installation.md
    - Gateware:
      - Top-Level:
          - Gateware Architecture: gw_architecture.md
          - Clocks and Reset: clocks_and_reset.md
          - Interrupts: interrupts.md
          - LEDs and Switches: leds_and_switches.md
          - FPGA Resource Utilization: fpga-resource-utilization.md
      - Gateware Components:
          - BoxLambda SoC: components_boxlambda_soc.md
          - Wishbone Interconnect: components_wb_interconnect.md
          - RISCV Ibex Processor: components_ibex.md
          - IMEM: components_imem.md
          - RISCV-DBG Debug Core: components_riscv_dbg.md
          - LiteDRAM Memory Controller: components_litedram.md
          - VERA (Wishbone) Graphics: components_vera.md
          - SDSPI SD Card Controller: components_sdspi.md
          - SPI Flash Controller: components_spiflash.md
          - Dual YM2149 PSG Sound Core: components_dual_ym2149.md
          - USB HID Keyboard and Mouse: components_usb_hid.md
          - UART: components_uart.md
          - GPIO: components_gpio.md
          - Timer: components_timer.md
          - I2C: components_i2c.md
          - RTCC: components_rtcc.md
          - VS0: components_vs0.md
          - DFX Controller: components_dfx_controller.md
      - Gateware Project Builds:
          - BoxLambda Base: gw_prj_build_boxlambda_base.md
          - BoxLambda DFX (Experimental/Advanced): gw_prj_build_boxlambda_dfx.md
      - Gateware Testing:
        - The Gateware Test Bench:
            - The Test Bench: gw-test-bench.md
            - The System-Level Test Bench: gw-test-bench-system-level.md
            - The Component-Level Test Bench: gw-test-bench-component-level.md
        - Gateware Test Builds:
            - Hello World: gw-test-build-hello-world.md
            - DDR Test: gw-test-build-ddr.md
            - VERA Test: gw-test-build-vera.md
            - SDSPI and FatFS Test: gw-test-build-sdspi-and-fatfs.md
            - YM2149 PSG, Audio DAC, and ST-Sound Test: gw-test-build-ym2149.md
            - USB HID Keyboard and Mouse Test: gw-test-build-usb-hid.md
            - SPI Flash Test: gw-test-build-spi-flash.md
            - Timer, UART, and GPIO Interrupt Test: gw-test-build-timer-uart-gpio-irqs.md
            - I2C Test: gw-test-build-i2c.md
            - Real-Time Clock and Calendar Test: gw-test-build-rtcc.md
            - Reset Test: gw-test-build-reset.md
            - DFX Test: gw-test-build-dfx.md
            - Invalid Address Test: gw-test-build-invalid-addr.md
            - Ibex Performance Test: gw-test-build-ibex-perf.md
    - Software:
      - OS Requirements: os_requirements.md
      - OS Architecture: os_architecture.md
      - OS Build: os_build.md
      - OS Memory Layout and Boot Sequence: os_mem_layout_boot_seq.md
      - Forth:
        - The Mecrisp Forth Core: forth-core.md
        - The Forth-C FFI: forth-c-ffi.md
        - Forth Word Glossary: forth-glossary.md
        - Interrupt Handling: forth_irqs.md
        - Time Handling: forth_time.md
      - Bootloader: sw_bootloader.md
      - C Components:
          - About C Components: c_comp_about.md
          - Register Access Layer: c_comp_register_access_layer.md
          - PicoLibc and the Bootstrap Component: c_comp_picolibc.md
          - LiteDRAM Initialization: c_comp_litedram_initialization.md
          - SDSPI: c_comp_sdspi.md
          - FatFs: c_comp_fat_fs.md
          - ST-Sound: c_comp_st_sound.md
          - VERA Stack: c_comp_vera_stack.md
          - USB HID: c_comp_usb_hid.md
          - Flash Driver: c_comp_flashdrvr.md
          - UART: c_comp_uart.md
          - GPIO: c_comp_gpio.md
          - RISC-V: c_comp_riscv.md
          - I2C: c_comp_i2c.md
          - Real-Time Clock and Calendar: c_comp_rtcc.md
          - DFX Controller HAL: c_comp_dfx_controller_hal.md
      - Test C Components:
          - About Test C Components: test_c_comp_about.md
          - Timer: test_c_comp_timer.md
          - Interrupt Handling: test_c_comp_irqs.md
          - Embedded CLI: test_c_comp_cli.md
          - Ymodem: test_c_comp_ymodem.md
          - Memory and File System CLI: test_c_comp_mem_fs_cli.md
          - Peek and Poke CLI: test_c_comp_peek_poke_cli.md
          - J1B HAL: test_c_comp_j1b_hal.md
          - VS0 HAL: test_c_comp_vs0_hal.md
      - Software Testing:
        - The Software Test Bench: sw-test-bench.md
        - Software Test Builds:
            - Forth Core Test: sw-test-build-forth-core.md
            - uLisp (Experimental): sw-test-build-ulisp.md
    - Build System:
        - The Directory Structure: build_sys_dir_struct.md
        - The Gateware Build System:
          - The Gateware Build Structure: build_sys_gw_build_struct.md
          - Building the Gateware: build_sys_building_gw.md
        - The Software Build System:
          - The Software Build Structure: build_sys_sw_build_struct.md
          - Building the Software: build_sys_building_sw.md
    - Register and Memory Map:
        - Reset: registers/generated/reset_regs.md
        - UART: registers/generated/uart_regs.md
        - GPIO: registers/generated/gpio_regs.md
        - MTIMER: registers/generated/mtimer_regs.md
        - I2C Master: registers/generated/i2c_master_regs.md
        - USB HID 0: registers/generated/usb_hid_0_regs.md
        - USB HID 1: registers/generated/usb_hid_1_regs.md
        - SDSPI: registers/generated/sdspi_regs.md
        - SPI Flash: registers/generated/spiflash_regs.md
        - VERA: registers/generated/vera_regs.md
        - YM2149: registers/generated/ym2149_regs.md
        - DFX Controller Control Register: registers/generated/dfx_controller_ctrl_reg.md
        - DFX Controller Other Registers: registers/generated/dfx_controller_other_regs.md
        - LiteDRAM Registers: litedram_regs.md
        - Memory Map: memory_map.md
    - Misc.:
      - Git Workflow: git-workflow.md
      - Documentation Builds:
          - Blog: doc-build-blog.md
          - MkDocs: doc-build-mkdocs.md


